---
kind: pipeline
name: python-3-6

steps:
- name: lint
  image: python:3.6
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - $HOME/.poetry/bin/poetry install -E lint
  - $HOME/.poetry/bin/poetry run black --check --diff .
  - $HOME/.poetry/bin/poetry run isort --check-only --diff --recursive -l 88
- name: build
  image: python:3.6
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - $HOME/.poetry/bin/poetry build

---
kind: pipeline
name: python-3-7

steps:
- name: lint
  image: python:3.7
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - $HOME/.poetry/bin/poetry install -E lint
  - $HOME/.poetry/bin/poetry run black --check --diff .
  - $HOME/.poetry/bin/poetry run isort --check-only --diff --recursive -l 88
- name: build
  image: python:3.7
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - $HOME/.poetry/bin/poetry build

---
kind: pipeline
name: python-3-8

steps:
- name: lint
  image: python:3.8
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - $HOME/.poetry/bin/poetry install -E lint
  - $HOME/.poetry/bin/poetry run black --check --diff .
  - $HOME/.poetry/bin/poetry run isort --check-only --diff --recursive -l 88
- name: build
  image: python:3.8
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - $HOME/.poetry/bin/poetry build

...
