---
kind: pipeline
name: python-3-6

steps:
- name: install poetry
  image: python:3.6
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
- name: lint
  image: python:3.6
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - $HOME/.poetry/bin/poetry install -E lint
  - $HOME/.poetry/bin/poetry run black --check --diff .
  - $HOME/.poetry/bin/poetry run isort --check-only --diff --recursive -l 88
- name: build
  image: python:3.6
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - $HOME/.poetry/bin/poetry build

volumes:
  - name: poetry-path
    temp: {}
  - name: poetry-venvs
    temp: {}
---
kind: pipeline
name: python-3-7

steps:
- name: install poetry
  image: python:3.7
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
- name: lint
  image: python:3.7
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - $HOME/.poetry/bin/poetry install -E lint
  - $HOME/.poetry/bin/poetry run black --check --diff .
  - $HOME/.poetry/bin/poetry run isort --check-only --diff --recursive -l 88
- name: build
  image: python:3.7
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - $HOME/.poetry/bin/poetry build

volumes:
  - name: poetry-path
    temp: {}
  - name: poetry-venvs
    temp: {}
---
kind: pipeline
name: python-3-8

steps:
- name: install poetry
  image: python:3.8
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
- name: lint
  image: python:3.8
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - $HOME/.poetry/bin/poetry install -E lint
  - $HOME/.poetry/bin/poetry run black --check --diff .
  - $HOME/.poetry/bin/poetry run isort --check-only --diff --recursive -l 88
- name: build
  image: python:3.8
  volumes:
    - name: poetry-path
      path: /root/.poetry
  commands:
  - $HOME/.poetry/bin/poetry build

volumes:
  - name: poetry-path
    temp: {}
  - name: poetry-venvs
    temp: {}
---
kind: signature
hmac: 59f3667fdc0a0260a94adbc97c3cfa5c68acc440ac3a98797823cd1cc8c292f6

...
